### ISSUE TITLE
Error when trying to play youtube video

### ISSUE THREAD

**Issue by Baconadors** [TheSharks/WildBeast#269]
First off, I am very new to this.

That being said, I followed the install instructions and have the bot in my server.
The issue rises whenever I try to play music. I'll get the following error:

> error:  error=Command failed: /home/ubuntu/WildBeast/node_modules/youtube-dl/bin/youtube-dl --dump-json -f best --skip-download -f bestaudio/worstvideo --add-header Authorization:KEYKEY http://www.youtube.com/watch?v=E1iwrfgNOUU
> /usr/bin/env: ‘python’: No such file or directory
> , done=true

I am running the bot on an AWS Ubuntu instance. How can I go about fixing this?

**Comment by zaza7** [comment]
Even though you edited this, I recommend you expire your key because well it's in my email so anyone else who is watching this repo may also have gotten it. As the error says, your system does not appear to have python, are you able to run `python --version` in the shell? If yes what version do you get back, if not well try to install it.

**Comment by Baconadors** [comment]
Thank you, I did invalidate the key.
Before starting the issue, I had tried installing python. I guess I just didn't finish. It's working now.
