### ISSUE TITLE
How to update?

### ISSUE THREAD

**Issue by ZandercraftGames** [TheSharks/WildBeast#354]
How do I update... i am de-coupled from docker?

**Comment by linuswillner** [comment]
Due to the faults in previous decoupling documentation, the former setup is not ideal. Presuming you have little to no data to lose:

1. Remove current Docker containers created by WildBeast (`docker-compose down` in the WB directory)
2. Pull the latest commit from master via Git
3. Proceed with the normal installation procedure for your platform. If you are fine with making changes and restarting the container, there’s no need to decouple. Otherwise you may do so following the guide for it.

**Comment by ZandercraftGames** [comment]
So if I de-couple it again... it will work?

**Comment by ZandercraftGames** [comment]
After the update?

**Comment by linuswillner** [comment]
So long as you follow the updated guide, yes.

**Comment by ZandercraftGames** [comment]
`INFO: Beginning startup sequence...
INFO: Scaling known. Total: 1, mine: 0
WARN: Git commit checking failed, falling back to version checking
INFO: Latest stable version: 6.1.1. Latest experimental version: 6.1.1
WARN: Not up-to-date with any remote version, update recommended
INFO: Fully ready, serving 498 guild(s).
ERROR: Error: connect ECONNREFUSED 192.168.99.100:2333
FATAL: Error: connect ECONNREFUSED 192.168.99.100:2333
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1161:14)`
Got this error

**Comment by ZandercraftGames** [comment]
This is while its on docker
I followed the instructions to the letter.

**Comment by ZandercraftGames** [comment]
Nevermind... old configs
Fixed.
